"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { richTextToHtml, isRichTextEmpty, type RichTextDoc } from "@/lib/rich-text";

/**
 * Question content — a stem, an option body, a passage or a solution.
 *
 * The public `RichText` component is a server component, which is right for
 * pages and wrong here: inside the player the content has to react to clicks,
 * because a dense DI chart or a geometry figure is unreadable at the width a
 * question column gives it. So this renders the same HTML from the same schema
 * and adds one behaviour — figures open full size.
 *
 * The `dangerouslySetInnerHTML` reasoning is the same as `RichText`'s: the
 * string is generated by walking a ProseMirror document against the schema, so
 * it cannot carry a node the schema does not define.
 */

export function QuestionContent({
  doc,
  className = "",
  /** Off for option bodies, where a click should select, not zoom. */
  zoomable = true,
}: {
  doc?: RichTextDoc | null;
  className?: string;
  zoomable?: boolean;
}) {
  const hostRef = useRef<HTMLDivElement>(null);
  const [zoomed, setZoomed] = useState<{ src: string; alt: string } | null>(null);

  const html = isRichTextEmpty(doc) ? "" : richTextToHtml(doc);

  /*
    Delegated rather than bound per image: the HTML is injected, so there are
    no React elements to attach handlers to, and re-querying on every content
    change would mean tracking teardown for each one.
  */
  const onClick = useCallback(
    (event: React.MouseEvent<HTMLDivElement>) => {
      if (!zoomable) return;
      const target = event.target as HTMLElement;
      if (target.tagName !== "IMG") return;
      const img = target as HTMLImageElement;
      setZoomed({ src: img.getAttribute("src") ?? "", alt: img.getAttribute("alt") ?? "" });
    },
    [zoomable],
  );

  // Figures are only reachable by keyboard if something makes them focusable,
  // and injected HTML carries no tabindex. Added after each render rather than
  // baked into the schema, so the stored document stays presentation-free.
  useEffect(() => {
    if (!zoomable || !hostRef.current) return;
    const images = hostRef.current.querySelectorAll("img");
    images.forEach((img) => {
      img.setAttribute("tabindex", "0");
      img.setAttribute("role", "button");
      img.style.cursor = "zoom-in";
      img.setAttribute(
        "aria-label",
        `${img.getAttribute("alt") ?? "Figure"} — activate to view full size`,
      );
    });
  }, [html, zoomable]);

  const onKeyDown = useCallback(
    (event: React.KeyboardEvent<HTMLDivElement>) => {
      if (!zoomable) return;
      if (event.key !== "Enter" && event.key !== " ") return;
      const target = event.target as HTMLElement;
      if (target.tagName !== "IMG") return;
      event.preventDefault();
      const img = target as HTMLImageElement;
      setZoomed({ src: img.getAttribute("src") ?? "", alt: img.getAttribute("alt") ?? "" });
    },
    [zoomable],
  );

  if (!html) return null;

  return (
    <>
      <div
        ref={hostRef}
        className={`rich-text ${className}`}
        onClick={onClick}
        onKeyDown={onKeyDown}
        dangerouslySetInnerHTML={{ __html: html }}
      />
      {zoomed && <FigureLightbox {...zoomed} onClose={() => setZoomed(null)} />}
    </>
  );
}

/**
 * Full-size figure view.
 *
 * Escape closes it, and the handler stops the event before the player's own
 * keyboard shortcuts see it — otherwise dismissing a zoomed chart would also
 * move the candidate to the next question.
 */
function FigureLightbox({
  src,
  alt,
  onClose,
}: {
  src: string;
  alt: string;
  onClose: () => void;
}) {
  const closeRef = useRef<HTMLButtonElement>(null);

  useEffect(() => {
    closeRef.current?.focus();

    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key !== "Escape") return;
      event.stopPropagation();
      onClose();
    };

    document.addEventListener("keydown", onKeyDown, true);
    const previous = document.body.style.overflow;
    document.body.style.overflow = "hidden";

    return () => {
      document.removeEventListener("keydown", onKeyDown, true);
      document.body.style.overflow = previous;
    };
  }, [onClose]);

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-label={alt || "Figure"}
      onClick={onClose}
      className="fixed inset-0 z-50 flex items-center justify-center bg-ink/80 p-4"
    >
      <button
        ref={closeRef}
        type="button"
        onClick={onClose}
        className="absolute right-4 top-4 rounded-lg bg-surface px-3 py-1.5 text-sm font-semibold text-ink shadow-lg"
      >
        Close
      </button>

      {/* eslint-disable-next-line @next/next/no-img-element --
          The source is a runtime string pulled out of rendered HTML, not a
          static import, and the optimizer adds nothing at full size. */}
      <img
        src={src}
        alt={alt}
        onClick={(event) => event.stopPropagation()}
        className="max-h-full max-w-full rounded-lg bg-surface object-contain shadow-2xl"
      />
    </div>
  );
}
